In [1]:
import torch
from PIL import Image
import requests
from lavis.models import load_model_and_preprocess

from torch import nn
import pandas as pd
import os

from tqdm.auto import tqdm, trange

from sklearn.metrics import classification_report
import json

from torch.utils.data import Dataset
import torch.utils.data as data
from torch import optim
from torch.autograd import Variable
import numpy as np
from sentence_transformers import util
from nltk.tokenize import TweetTokenizer
import re, string

/homes/yg007/nytimes_project/venv_nyc/lib/python3.7/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
# from lavis.models import model_zoo

In [3]:
# print(model_zoo)

In [4]:
# import os
# os.environ["CUDA_DEVICE_ORDER"]="PCI_BUS_ID"   # see issue #152
# os.environ["CUDA_VISIBLE_DEVICES"]="1,2,3"

# Load the model

In [5]:
# setup device to use
device = torch.device("cuda") if torch.cuda.is_available() else "cpu"
print(device)

cuda


In [6]:
model, vis_processors, txt_processors = load_model_and_preprocess(
    name = "clip_feature_extractor", model_type="ViT-B-32", is_eval=True, device=device
)

In [7]:
tt = TweetTokenizer()

# Define the Dataset class

In [8]:
class TwitterCOMMsDataset(Dataset):
    def __init__(self, csv_path, img_dir):
        """
        Args:
            csv_path (string): Path to the {train_completed|val_completed}.csv file.
            image_folder_dir (string): Directory containing the images
        """
        self.df = pd.read_csv(csv_path, index_col=0)
        self.img_dir = img_dir
        
        self.df['exists'] = self.df['filename'].apply(lambda filename: os.path.exists(os.path.join(img_dir, filename)))
        delete_row = self.df[self.df["exists"]==False].index
        self.df = self.df.drop(delete_row)
    
    def __len__(self):
        return len(self.df)
    
    def remove_URL(self, text):
        """Remove URLs from a sample string"""
        return re.sub(r"http\S+", '', text)
    
    def remove_punc(self, text):
        """Remove punctuation from a sample string"""
        return re.sub(r'[^\w\s]', '', text)

    def __getitem__(self, idx):
        item = self.df.iloc[idx]
        
        topic = item['topic']
        falsified = int(item['falsified'])
        not_falsified = float(not item['falsified'])
#         label = np.array((falsified, not_falsified))
        label = np.array(falsified)
        domain = topic.split('_')[0]
        diff = topic.split('_')[1]
        
        # Preprocess the text
        caption = item['full_text']
        caption = ' '.join(tt.tokenize(caption))
        caption = self.remove_punc(self.remove_URL(caption))
        
        # Open the image
        img_filename = item['filename']
        raw_image = Image.open(os.path.join(self.img_dir, img_filename)).convert('RGB')
        
        # Get the multimodal embedding
        image = vis_processors["eval"](raw_image).unsqueeze(0).to(device)
        text_input = txt_processors["eval"](caption)
        sample = {"image": image, "text_input": [text_input]}   # image shape: [1, 3, 224, 224]
        features = model.extract_features(sample)
        features_image = features.image_embeds   # [1, 512]
        features_text = features.text_embeds   # [1, 512]
#         multimodal_emb = torch.cat((features_image, features_text), 1)
        multimodal_emb = features_image * features_text
        
        cos_sim = util.cos_sim(features_text, features_image)
#         features_image_proj = features_image.image_embeds_proj[:,0,:]   # [1, 256]
#         features_text_proj = features_text.text_embeds_proj[:,0,:]   # [1, 256]
        
#         multimodal_emb = torch.cat((features_image_proj, features_text_proj), 1)
#         multimodal_emb = features_image_proj * features_text_proj   # [1, 256]
#         print(multimodal_emb.shape)

#         similarity = features_image_proj @ features_text_proj.t()

        return {"multimodal_emb": multimodal_emb,
                "topic": topic, 
                "label": label, 
                "domain": domain, 
                "difficulty": diff,
               "similarity": cos_sim}
        
        
        
    

In [9]:
# class ClimateAndCovidDataset(Dataset):
#     def __init__(self, csv_path, img_dir):
#         """
#         Args:
#             csv_path (string): Path to the {train_completed|val_completed}.csv file.
#             image_folder_dir (string): Directory containing the images
#         """
#         self.df = pd.read_csv(csv_path, index_col=0)
#         self.img_dir = img_dir
        
#         self.df['exists'] = self.df['filename'].apply(lambda filename: os.path.exists(os.path.join(img_dir, filename)))
#         delete_row = self.df[self.df["exists"]==False].index
#         self.df = self.df.drop(delete_row)
        
#         self.df['is_military'] = self.df['topic'].apply(lambda topic: 'military' in topic)
#         delete_row = self.df[self.df["is_military"]==True].index
#         self.df = self.df.drop(delete_row)
    
#     def __len__(self):
#         return len(self.df)

#     def __getitem__(self, idx):
#         item = self.df.iloc[idx]
#         caption = item['full_text']
#         img_filename = item['filename']
#         topic = item['topic']
#         falsified = float(item['falsified'])
#         not_falsified = float(not item['falsified'])
#         label = np.array((falsified, not_falsified))
#         domain = topic.split('_')[0]
#         diff = topic.split('_')[1]
        
#         try:
#             raw_image = Image.open(os.path.join(self.img_dir, img_filename)).convert('RGB')
#             image = vis_processors["eval"](raw_image).unsqueeze(0).to(device)
#             text_input = txt_processors["eval"](caption)
#             sample = {"image": image, "text_input": [text_input]}   # image shape: [1, 3, 224, 224]
        
#             features_multimodal = model.extract_features(sample, mode="multimodal")
# #             features_image = model.extract_features(sample, mode="image")
# #             features_text = model.extract_features(sample, mode="text")
# #             print(features_multimodal.multimodal_embeds[:, 0, :].shape)
        
#             return {"multimodal_emb": features_multimodal.multimodal_embeds[:, 0, :],
#                     "topic": topic, 
#                     "label": label, 
#                     "domain": domain, 
#                     "difficulty": diff}
        
#         except IOError as e:
#             print(e)
        
        
        
    

In [10]:
# train_data = TwitterCOMMsDataset(csv_path='../data/train_completed.csv',
#                                     img_dir='/import/network-temp/yimengg/data/twitter-comms/train/images/train_image_ids')   # took ~one hour to construct the dataset
val_data = TwitterCOMMsDataset(csv_path='../data/val_completed.csv', 
                               img_dir='/import/network-temp/yimengg/data/twitter-comms/images/val_images/val_tweet_image_ids')

In [11]:
val_data[0]['multimodal_emb'].shape

torch.Size([1, 512])

In [12]:
# train_data.__len__()

In [13]:
BATCH_SIZE = 32

# train_iterator = data.DataLoader(train_data, 
#                                  shuffle = True, 
#                                  batch_size=BATCH_SIZE)
val_iterator = data.DataLoader(val_data, 
                               shuffle = False, 
                               batch_size=BATCH_SIZE)

In [14]:
class Net(nn.Module):
    def __init__(self, in_dim, out_dim=2):
        super(Net, self).__init__()
        
        self.fc = nn.Linear(in_dim, out_dim)
        self.in_dim = in_dim
    
    def forward(self, x):
        x = x.view(-1, self.in_dim)
        out = self.fc(x)
        return out
    
    def weight_init(self, mean, std):
        for m in self._modules:
            normal_init(self._modules[m], mean, std)

In [15]:
def normal_init(m, mean, std):
    if isinstance(m, nn.Linear):
        m.weight.data.normal_(mean, std)
        m.bias.data.zero_()

In [20]:
def main():
    net = Net(512)
#     net = Net(1024)
    net.cuda()
    net.train()
    net.weight_init(mean=0, std=0.02)
    
    lr = 0.0001
    optimizer = optim.Adam(net.parameters(), lr=lr, betas=(0.5, 0.999), weight_decay=1e-5)
    
    criterion = nn.CrossEntropyLoss()
    criterion.to(device)
    
    softmax = nn.Softmax(dim=1)
 
    EPOCHS = 2
    for epoch in range(EPOCHS):
        total_loss = 0
        num_correct = 0
        total = 0
        for i, batch in tqdm(enumerate(val_iterator, 0), desc='iterations'):
            inputs = batch["multimodal_emb"].to(device)
            labels = batch["label"].to(device)
            inputs, labels = Variable(inputs), Variable(labels)
            
            net.zero_grad()
            y_preds = net(inputs)
            loss = criterion(y_preds, labels)
            
            loss.backward()
            optimizer.step()
            
            total_loss += loss.item()
            
#             _, top_pred = y_preds.topk(1, 1)
            
            top_pred = torch.zeros_like(labels)
            y_preds = softmax(y_preds)
#             print(y_preds[:, 0])
            top_pred[y_preds[:, 1] >= 0.5] = 1
            y = labels.cpu()
            batch_size = y.shape[0]
            top_pred = top_pred.cpu().view(batch_size)
            
#             num_correct += sum(top_pred == y[:, 0]).item()
            num_correct += sum(top_pred == y).item()
            total += batch_size
            
            if i % 50 == 0:
                print("Epoch [%d/%d]: Training accuracy %.2f, training loss %.3f" % (epoch+1, EPOCHS, num_correct/total, total_loss/total))
                print(y_preds[:, 1])
#                 print(top_pred)
#                 print(labels)
#                 print(num_correct)
#                 print(total)

    return net

In [21]:
net = main()

iterations: 1it [00:01,  1.65s/it]

Epoch [1/2]: Training accuracy 0.56, training loss 0.022
tensor([0.4662, 0.4662, 0.4780, 0.4651, 0.4848, 0.4562, 0.4837, 0.4837, 0.4893,
        0.4970, 0.4970, 0.4867, 0.4793, 0.4793, 0.4764, 0.4680, 0.4674, 0.4655,
        0.4655, 0.4979, 0.5008, 0.5283, 0.5283, 0.5076, 0.4800, 0.4800, 0.4818,
        0.5099, 0.5035, 0.4918, 0.4918, 0.4911], device='cuda:0',
       grad_fn=<SelectBackward0>)


iterations: 51it [01:49,  2.73s/it]

Epoch [1/2]: Training accuracy 0.53, training loss 0.022
tensor([0.4662, 0.4916, 0.4608, 0.5038, 0.5038, 0.5075, 0.5075, 0.4882, 0.5114,
        0.4845, 0.4845, 0.4939, 0.5137, 0.4949, 0.4949, 0.4915, 0.4845, 0.4845,
        0.4754, 0.4639, 0.4498, 0.4498, 0.4770, 0.4947, 0.4947, 0.4901, 0.4670,
        0.5153, 0.4863, 0.4863, 0.5044, 0.4761], device='cuda:0',
       grad_fn=<SelectBackward0>)


iterations: 101it [03:21,  1.89s/it]

Epoch [1/2]: Training accuracy 0.53, training loss 0.022
tensor([0.4479, 0.4690, 0.4640, 0.4640, 0.4708, 0.4545, 0.4382, 0.4382, 0.4401,
        0.4401, 0.4997, 0.4889, 0.4564, 0.4693, 0.4693, 0.4754, 0.4646, 0.4646,
        0.4780, 0.4667, 0.4940, 0.4536, 0.4536, 0.4514, 0.4676, 0.4676, 0.4763,
        0.5014, 0.4794, 0.4978, 0.4814, 0.4814], device='cuda:0',
       grad_fn=<SelectBackward0>)


iterations: 151it [05:05,  2.09s/it]

Epoch [1/2]: Training accuracy 0.55, training loss 0.021
tensor([0.5078, 0.4945, 0.4693, 0.4644, 0.4644, 0.4923, 0.4732, 0.4451, 0.4451,
        0.4605, 0.4680, 0.4880, 0.4880, 0.4938, 0.4813, 0.4554, 0.4554, 0.4633,
        0.4809, 0.4744, 0.4612, 0.4612, 0.4164, 0.4164, 0.5066, 0.4826, 0.4629,
        0.4251, 0.4251, 0.4868, 0.4771, 0.4771], device='cuda:0',
       grad_fn=<SelectBackward0>)


iterations: 201it [06:41,  2.22s/it]

Epoch [1/2]: Training accuracy 0.56, training loss 0.021
tensor([0.4494, 0.4494, 0.4583, 0.4583, 0.5114, 0.4812, 0.4774, 0.4774, 0.4903,
        0.5156, 0.5000, 0.4901, 0.4901, 0.5071, 0.4839, 0.4560, 0.4560, 0.4451,
        0.4451, 0.4567, 0.4574, 0.4581, 0.4633, 0.4633, 0.4895, 0.4947, 0.4299,
        0.4299, 0.4604, 0.4988, 0.4739, 0.4739], device='cuda:0',
       grad_fn=<SelectBackward0>)


iterations: 251it [08:23,  2.29s/it]

Epoch [1/2]: Training accuracy 0.57, training loss 0.021
tensor([0.4606, 0.4606, 0.4558, 0.4858, 0.4689, 0.4761, 0.4246, 0.4246, 0.5073,
        0.4572, 0.4572, 0.5005, 0.5072, 0.4997, 0.4997, 0.4672, 0.4906, 0.4816,
        0.4816, 0.4599, 0.4509, 0.4509, 0.4520, 0.5154, 0.4548, 0.4548, 0.4912,
        0.4323, 0.4856, 0.4466, 0.4466, 0.4635], device='cuda:0',
       grad_fn=<SelectBackward0>)


iterations: 301it [09:47,  1.54s/it]

Epoch [1/2]: Training accuracy 0.58, training loss 0.021
tensor([0.4218, 0.4218, 0.4814, 0.4596, 0.4120, 0.4200, 0.4200, 0.4898, 0.5205,
        0.5205, 0.4628, 0.4628, 0.5096, 0.5129, 0.5236, 0.4144, 0.4189, 0.4189,
        0.4380, 0.4380, 0.4931, 0.4699, 0.4514, 0.4514, 0.4523, 0.4523, 0.4823,
        0.5074, 0.4614, 0.4220, 0.4220, 0.4760], device='cuda:0',
       grad_fn=<SelectBackward0>)


iterations: 351it [11:17,  1.47s/it]

Epoch [1/2]: Training accuracy 0.58, training loss 0.021
tensor([0.4208, 0.4198, 0.4512, 0.4512, 0.4573, 0.4386, 0.4162, 0.4162, 0.4472,
        0.4472, 0.4530, 0.4160, 0.4535, 0.4535, 0.4571, 0.4957, 0.4712, 0.4744,
        0.4744, 0.3939, 0.3939, 0.4618, 0.4642, 0.4365, 0.4365, 0.5093, 0.4766,
        0.4766, 0.5004, 0.4118, 0.4563, 0.3756], device='cuda:0',
       grad_fn=<SelectBackward0>)


iterations: 401it [12:55,  2.69s/it]

Epoch [1/2]: Training accuracy 0.59, training loss 0.021
tensor([0.4840, 0.4896, 0.4822, 0.4596, 0.4596, 0.4541, 0.4833, 0.3999, 0.3999,
        0.4426, 0.4845, 0.4382, 0.4382, 0.4499, 0.4499, 0.5082, 0.4643, 0.4643,
        0.4596, 0.3824, 0.3824, 0.4528, 0.5053, 0.4837, 0.5039, 0.4449, 0.4449,
        0.4059, 0.4059, 0.4324, 0.4082, 0.4972], device='cuda:0',
       grad_fn=<SelectBackward0>)


iterations: 451it [14:23,  1.55s/it]

Epoch [1/2]: Training accuracy 0.60, training loss 0.021
tensor([0.4339, 0.4339, 0.3987, 0.3987, 0.4917, 0.4748, 0.3872, 0.3462, 0.3462,
        0.3746, 0.4325, 0.5244, 0.4355, 0.4355, 0.4421, 0.4421, 0.4799, 0.5147,
        0.5147, 0.5129, 0.4937, 0.3358, 0.3358, 0.4361, 0.4863, 0.4305, 0.4305,
        0.4221, 0.4221, 0.4648, 0.4053, 0.3405], device='cuda:0',
       grad_fn=<SelectBackward0>)


iterations: 501it [15:56,  1.35s/it]

Epoch [1/2]: Training accuracy 0.60, training loss 0.021
tensor([0.4076, 0.4523, 0.3927, 0.3927, 0.4034, 0.5016, 0.4214, 0.4214, 0.4875,
        0.3766, 0.3766, 0.4209, 0.3476, 0.3896, 0.4508, 0.3765, 0.3765, 0.4440,
        0.4056, 0.4109, 0.4109, 0.4511, 0.4135, 0.4135, 0.4564, 0.4723, 0.4202,
        0.4312, 0.4312, 0.3843, 0.3843, 0.4219], device='cuda:0',
       grad_fn=<SelectBackward0>)


iterations: 551it [17:24,  1.67s/it]

Epoch [1/2]: Training accuracy 0.59, training loss 0.021
tensor([0.3716, 0.4909, 0.5549, 0.4794, 0.4728, 0.4728, 0.5374, 0.4578, 0.4238,
        0.4238, 0.4516, 0.4516, 0.4418, 0.4746, 0.4273, 0.4711, 0.4180, 0.4180,
        0.5104, 0.3748, 0.4139, 0.4139, 0.4465, 0.4465, 0.4172, 0.4431, 0.4388,
        0.4872, 0.4468, 0.4468, 0.5254, 0.4179], device='cuda:0',
       grad_fn=<SelectBackward0>)


iterations: 601it [18:53,  2.25s/it]

Epoch [1/2]: Training accuracy 0.60, training loss 0.021
tensor([0.3445, 0.4939, 0.3580, 0.4213, 0.4213, 0.5029, 0.4632, 0.4583, 0.3926,
        0.4110, 0.4110, 0.5265, 0.4903, 0.4903, 0.4552, 0.4707, 0.4707, 0.4507,
        0.4312, 0.4456, 0.3539, 0.3539, 0.4511, 0.4061, 0.4061, 0.3980, 0.4777,
        0.4236, 0.4236, 0.4575, 0.4224, 0.4982], device='cuda:0',
       grad_fn=<SelectBackward0>)


iterations: 651it [20:32,  1.91s/it]

Epoch [1/2]: Training accuracy 0.60, training loss 0.021
tensor([0.4804, 0.4804, 0.4392, 0.4382, 0.4382, 0.4480, 0.4543, 0.4543, 0.5195,
        0.4624, 0.4139, 0.4139, 0.4930, 0.4316, 0.4720, 0.3766, 0.3766, 0.5009,
        0.5009, 0.5251, 0.5650, 0.4631, 0.4631, 0.4646, 0.5406, 0.4635, 0.4377,
        0.4377, 0.5252, 0.5252, 0.5340, 0.5196], device='cuda:0',
       grad_fn=<SelectBackward0>)


iterations: 691it [21:41,  1.88s/it]
iterations: 1it [00:01,  1.55s/it]

Epoch [2/2]: Training accuracy 0.72, training loss 0.020
tensor([0.4070, 0.4070, 0.4644, 0.5267, 0.4773, 0.4849, 0.4427, 0.4427, 0.5522,
        0.3656, 0.3656, 0.5475, 0.5829, 0.5829, 0.6039, 0.5547, 0.5023, 0.4535,
        0.4535, 0.6189, 0.4890, 0.4773, 0.4773, 0.4901, 0.3882, 0.3882, 0.5019,
        0.5513, 0.5502, 0.5446, 0.5446, 0.5802], device='cuda:0',
       grad_fn=<SelectBackward0>)


iterations: 51it [01:45,  2.77s/it]

Epoch [2/2]: Training accuracy 0.70, training loss 0.020
tensor([0.4423, 0.4458, 0.4483, 0.4666, 0.4666, 0.4117, 0.4117, 0.6216, 0.4790,
        0.4087, 0.4087, 0.5700, 0.5511, 0.3758, 0.3758, 0.5516, 0.4504, 0.4504,
        0.4359, 0.4517, 0.4546, 0.4546, 0.5333, 0.4916, 0.4916, 0.5440, 0.5265,
        0.4949, 0.3825, 0.3825, 0.5206, 0.5968], device='cuda:0',
       grad_fn=<SelectBackward0>)


iterations: 101it [03:15,  1.79s/it]

Epoch [2/2]: Training accuracy 0.70, training loss 0.020
tensor([0.4353, 0.5096, 0.4796, 0.4796, 0.5669, 0.4779, 0.3680, 0.3680, 0.4152,
        0.4152, 0.5693, 0.5739, 0.4732, 0.4886, 0.4886, 0.5524, 0.4835, 0.4835,
        0.5798, 0.5349, 0.6425, 0.3831, 0.3831, 0.4456, 0.5190, 0.5190, 0.5569,
        0.5617, 0.4897, 0.5521, 0.3594, 0.3594], device='cuda:0',
       grad_fn=<SelectBackward0>)


iterations: 151it [04:58,  1.99s/it]

Epoch [2/2]: Training accuracy 0.70, training loss 0.020
tensor([0.5066, 0.4697, 0.5177, 0.4148, 0.4148, 0.5479, 0.4923, 0.3651, 0.3651,
        0.3865, 0.5213, 0.5311, 0.5311, 0.5833, 0.5425, 0.5106, 0.5106, 0.5421,
        0.4506, 0.4223, 0.4325, 0.4325, 0.3142, 0.3142, 0.5928, 0.5172, 0.4119,
        0.3005, 0.3005, 0.5317, 0.4375, 0.4375], device='cuda:0',
       grad_fn=<SelectBackward0>)


iterations: 201it [06:34,  2.24s/it]

Epoch [2/2]: Training accuracy 0.71, training loss 0.020
tensor([0.3656, 0.3656, 0.3717, 0.3717, 0.5463, 0.4518, 0.5568, 0.5568, 0.6029,
        0.6250, 0.5200, 0.5408, 0.5408, 0.6119, 0.4506, 0.3822, 0.3822, 0.3601,
        0.3601, 0.4734, 0.4541, 0.3761, 0.3629, 0.3629, 0.5203, 0.4682, 0.3165,
        0.3165, 0.4158, 0.5370, 0.4784, 0.4784], device='cuda:0',
       grad_fn=<SelectBackward0>)


iterations: 251it [08:16,  2.35s/it]

Epoch [2/2]: Training accuracy 0.71, training loss 0.019
tensor([0.4489, 0.4489, 0.4446, 0.5545, 0.4800, 0.5082, 0.3718, 0.3718, 0.5753,
        0.4407, 0.4407, 0.5268, 0.5110, 0.5644, 0.5644, 0.4816, 0.5391, 0.4492,
        0.4492, 0.4537, 0.3469, 0.3469, 0.4152, 0.6200, 0.4667, 0.4667, 0.5513,
        0.4061, 0.5408, 0.4337, 0.4337, 0.4308], device='cuda:0',
       grad_fn=<SelectBackward0>)


iterations: 301it [09:41,  1.69s/it]

Epoch [2/2]: Training accuracy 0.71, training loss 0.019
tensor([0.3416, 0.3416, 0.5788, 0.4418, 0.3367, 0.3279, 0.3279, 0.5567, 0.6204,
        0.6204, 0.4283, 0.4283, 0.5696, 0.5864, 0.5880, 0.3567, 0.3618, 0.3618,
        0.3995, 0.3995, 0.5406, 0.5076, 0.4407, 0.4407, 0.4353, 0.4353, 0.4930,
        0.5642, 0.4989, 0.4208, 0.4208, 0.5367], device='cuda:0',
       grad_fn=<SelectBackward0>)


iterations: 351it [11:14,  1.55s/it]

Epoch [2/2]: Training accuracy 0.71, training loss 0.019
tensor([0.3780, 0.3560, 0.4274, 0.4274, 0.5132, 0.3871, 0.3949, 0.3949, 0.4931,
        0.4931, 0.4607, 0.3628, 0.4528, 0.4528, 0.4567, 0.5709, 0.5131, 0.5247,
        0.5247, 0.2515, 0.2515, 0.4115, 0.4327, 0.3895, 0.3895, 0.5579, 0.5413,
        0.5413, 0.5575, 0.3871, 0.5051, 0.2752], device='cuda:0',
       grad_fn=<SelectBackward0>)


iterations: 401it [12:58,  2.93s/it]

Epoch [2/2]: Training accuracy 0.71, training loss 0.019
tensor([0.5506, 0.5249, 0.5258, 0.4674, 0.4674, 0.4713, 0.5260, 0.2981, 0.2981,
        0.4074, 0.5400, 0.3839, 0.3839, 0.4523, 0.4523, 0.5877, 0.4657, 0.4657,
        0.4794, 0.3133, 0.3133, 0.4846, 0.5594, 0.5410, 0.5438, 0.4435, 0.4435,
        0.3825, 0.3825, 0.4103, 0.3730, 0.5429], device='cuda:0',
       grad_fn=<SelectBackward0>)


iterations: 451it [14:30,  1.56s/it]

Epoch [2/2]: Training accuracy 0.71, training loss 0.019
tensor([0.4171, 0.4171, 0.3187, 0.3187, 0.5059, 0.4730, 0.3516, 0.2661, 0.2661,
        0.3397, 0.4535, 0.5815, 0.4665, 0.4665, 0.4851, 0.4851, 0.5783, 0.5946,
        0.5946, 0.5915, 0.5261, 0.2397, 0.2397, 0.4418, 0.5168, 0.4177, 0.4177,
        0.4173, 0.4173, 0.4906, 0.4090, 0.3217], device='cuda:0',
       grad_fn=<SelectBackward0>)


iterations: 501it [16:07,  1.41s/it]

Epoch [2/2]: Training accuracy 0.71, training loss 0.019
tensor([0.4104, 0.5076, 0.3763, 0.3763, 0.3924, 0.5733, 0.3611, 0.3611, 0.5438,
        0.3423, 0.3423, 0.4490, 0.2999, 0.3592, 0.5075, 0.3335, 0.3335, 0.4843,
        0.3932, 0.3924, 0.3924, 0.4829, 0.4265, 0.4265, 0.4831, 0.5201, 0.4124,
        0.4120, 0.4120, 0.3532, 0.3532, 0.4072], device='cuda:0',
       grad_fn=<SelectBackward0>)


iterations: 551it [17:37,  1.68s/it]

Epoch [2/2]: Training accuracy 0.71, training loss 0.019
tensor([0.2901, 0.4953, 0.6285, 0.4962, 0.4824, 0.4824, 0.5863, 0.4829, 0.4042,
        0.4042, 0.4739, 0.4739, 0.4377, 0.5017, 0.4462, 0.4787, 0.4170, 0.4170,
        0.5552, 0.3231, 0.3853, 0.3853, 0.4428, 0.4428, 0.4004, 0.4252, 0.4192,
        0.4981, 0.4361, 0.4361, 0.6070, 0.4165], device='cuda:0',
       grad_fn=<SelectBackward0>)


iterations: 601it [19:07,  2.24s/it]

Epoch [2/2]: Training accuracy 0.70, training loss 0.019
tensor([0.2586, 0.5460, 0.2935, 0.3680, 0.3680, 0.5789, 0.4646, 0.4564, 0.3394,
        0.3702, 0.3702, 0.5956, 0.5500, 0.5500, 0.4736, 0.4809, 0.4809, 0.4583,
        0.4248, 0.4585, 0.3036, 0.3036, 0.4746, 0.3671, 0.3671, 0.3572, 0.5105,
        0.3937, 0.3937, 0.4639, 0.4014, 0.5345], device='cuda:0',
       grad_fn=<SelectBackward0>)


iterations: 651it [20:45,  1.90s/it]

Epoch [2/2]: Training accuracy 0.70, training loss 0.019
tensor([0.4919, 0.4919, 0.4307, 0.4311, 0.4311, 0.4667, 0.4553, 0.4553, 0.5320,
        0.4723, 0.3911, 0.3911, 0.5026, 0.4012, 0.4961, 0.3398, 0.3398, 0.4972,
        0.4972, 0.5515, 0.6199, 0.4279, 0.4279, 0.4519, 0.6008, 0.4721, 0.4071,
        0.4071, 0.5791, 0.5791, 0.5849, 0.5849], device='cuda:0',
       grad_fn=<SelectBackward0>)


iterations: 691it [21:54,  1.90s/it]


In [ ]:
!nvidia-smi

In [22]:
num_correct = 0
total = 0
for i, batch in tqdm(enumerate(val_iterator, 0), desc='iterations'):
    similarity = batch["similarity"].squeeze()
    labels = batch["label"]
    y_preds = torch.zeros_like(labels)
#     y_preds[similarity < 0.25] = 1
    y_preds[similarity < 0.5] = 1
    
    num_correct += sum(y_preds == labels).item()
    total += BATCH_SIZE
    
    if i % 50 == 0:
        print("Accuracy %.2f" % (num_correct/total))
        print(y_preds)
        print(similarity)

iterations: 1it [00:01,  1.54s/it]

Accuracy 0.50
tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1])
tensor([0.3349, 0.3349, 0.2642, 0.1821, 0.2555, 0.2151, 0.3025, 0.3025, 0.2159,
        0.3478, 0.3478, 0.2324, 0.2302, 0.2302, 0.2318, 0.2411, 0.2512, 0.2805,
        0.2805, 0.1719, 0.2577, 0.2763, 0.2763, 0.2854, 0.3493, 0.3493, 0.2674,
        0.1792, 0.1598, 0.2364, 0.2364, 0.1451], device='cuda:0',
       grad_fn=<SqueezeBackward0>)


iterations: 51it [01:48,  2.79s/it]

Accuracy 0.49
tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1])
tensor([0.2013, 0.2949, 0.2541, 0.2889, 0.2889, 0.3252, 0.3252, 0.1864, 0.2455,
        0.3206, 0.3206, 0.2248, 0.1014, 0.3531, 0.3531, 0.2052, 0.2658, 0.2658,
        0.2847, 0.2716, 0.2694, 0.2694, 0.1450, 0.2631, 0.2631, 0.1578, 0.2307,
        0.2952, 0.3938, 0.3938, 0.2566, 0.2436], device='cuda:0',
       grad_fn=<SqueezeBackward0>)


iterations: 57it [02:00,  2.12s/it]


KeyboardInterrupt: 

# Playground

In [ ]:
val_df = pd.read_csv('../data/val_completed.csv', index_col=0)
val_df

In [ ]:
img_dir = '/import/network-temp/yimengg/data/twitter-comms/images/val_images/val_tweet_image_ids'
val_df['exists'] = val_df['filename'].apply(lambda filename: os.path.exists(os.path.join(img_dir, filename)))

In [ ]:
delete_row = val_df[val_df["exists"]==False].index

In [ ]:
val_df = val_df.drop(delete_row)

In [ ]:
val_df

In [ ]:
def remove_URL(text):
    """Remove URLs from a sample string"""
    return re.sub(r"http\S+", '', text)

def remove_punc(text):
    """Remove punctuation from a sample string"""
    return re.sub(r'[^\w\s]', '', text)

s = val_data.df.iloc[0]['full_text']
print(s)
s = ' '.join(tt.tokenize(s))
print(remove_punc(remove_URL(s)))

In [ ]:
idx = 6
print(val_data.df.iloc[idx]['full_text'])
print("Falsified? " + str(val_data.df.iloc[idx]['falsified']))
print(val_data.df.iloc[idx]['topic'])
print(val_data[idx]['similarity'])

raw_image = Image.open('/import/network-temp/yimengg/data/twitter-comms/images/val_images/val_tweet_image_ids/'+val_data.df.iloc[idx]['filename']).convert('RGB')   
display(raw_image.resize((596, 437)))